version: "3"
services:
  postgres:
    image: postgres:11.2
    ports:
    - "5432:5432"
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - ./redis/data:/data
